name: 'Check & Publish utils package'

on: push

jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
      uses: JS-DevTools/npm-publish@v1
      id: utils
        with:
        token: ${{ secrets.NPM_TOKEN }}
        package: "./packages/utils/package.json"